<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('histories', function (Blueprint $table) {

            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Operation / Batch
            |--------------------------------------------------------------------------
            |
            | Identifies a group of history records generated by the same
            | business operation or transactional process.
            |
            | Multiple entities may share the same batch_uuid when they are
            | modified as part of a single business operation.
            |
            */

            $table->uuid('batch_uuid')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Root Entity
            |--------------------------------------------------------------------------
            |
            | Identifies the main or aggregate root entity to which the
            | historical record belongs.
            |
            | This allows multiple related entities to be grouped under
            | the same root entity while maintaining their own identity.
            |
            | root_entity_type:
            | Stores the class or type of the root entity.
            |
            | root_entity_uuid:
            | Stores the unique identifier of the root entity.
            |
            */

            $table->string('root_entity_type')
                ->nullable();

            $table->uuid('root_entity_uuid')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Entity
            |--------------------------------------------------------------------------
            |
            | Identifies the specific entity that generated the history record.
            |
            | The entity may be the root entity itself or a related entity
            | belonging to the same aggregate or business context.
            |
            */

            $table->string('entity_type');

            $table->unsignedBigInteger('entity_id')
                ->nullable();

            $table->uuid('entity_uuid')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Changed Field
            |--------------------------------------------------------------------------
            |
            | Stores the name of the specific field affected by the operation.
            |
            | This value may be null when the history record represents
            | an operation over the entire entity.
            |
            */

            $table->string('field')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Logical Path
            |--------------------------------------------------------------------------
            |
            | Stores the logical location of the affected property within
            | a nested entity structure.
            |
            | This can be used to represent relationships between entities
            | or nested attributes.
            |
            */

            $table->string('path')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Previous / New Values
            |--------------------------------------------------------------------------
            |
            | Stores the state before and after the operation.
            |
            | These values allow the system to reconstruct what changed
            | without modifying or duplicating the original entity records.
            |
            */

            $table->json('old_value')
                ->nullable();

            $table->json('new_value')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Action
            |--------------------------------------------------------------------------
            |
            | Identifies the type of operation performed.
            |
            | Examples:
            |
            | created
            | updated
            | deleted
            |
            */

            $table->string('action');

            /*
            |--------------------------------------------------------------------------
            | User
            |--------------------------------------------------------------------------
            |
            | Identifies the authenticated user responsible for the operation.
            |
            */

            $table->foreignId('user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Additional Information
            |--------------------------------------------------------------------------
            */

            $table->text('description')
                ->nullable();

            $table->ipAddress('ip_address')
                ->nullable();

            $table->text('user_agent')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Timestamps
            |--------------------------------------------------------------------------
            */

            $table->timestamps();

            /*
            |--------------------------------------------------------------------------
            | Indexes
            |--------------------------------------------------------------------------
            */

            // Groups history records belonging to the same operation.
            $table->index(
                'batch_uuid',
                'histories_batch_uuid_index'
            );

            // Retrieves the complete history of a root entity.
            $table->index(
                [
                    'root_entity_type',
                    'root_entity_uuid',
                ],
                'histories_root_entity_index'
            );

            // Retrieves history records by internal entity identifier.
            $table->index(
                [
                    'entity_type',
                    'entity_id',
                ],
                'histories_entity_id_index'
            );

            // Retrieves history records by entity UUID.
            $table->index(
                [
                    'entity_type',
                    'entity_uuid',
                ],
                'histories_entity_uuid_index'
            );

            // Filters history records by operation type.
            $table->index(
                'action',
                'histories_action_index'
            );

            // Retrieves history records generated by a specific user.
            $table->index(
                'user_id',
                'histories_user_id_index'
            );

            // Supports chronological queries.
            $table->index(
                'created_at',
                'histories_created_at_index'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('histories');
    }
};