<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('histories', function (Blueprint $table) {

            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Operation / Batch
            |--------------------------------------------------------------------------
            |
            | Groups all changes generated by the same business operation.
            | Example: one UpdateQuotationAction can generate multiple history rows.
            |
            */

            $table->uuid('batch_uuid')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Entity
            |--------------------------------------------------------------------------
            */

            $table->string('entity_type');

            $table->unsignedBigInteger('entity_id')
                ->nullable();

            $table->uuid('entity_uuid')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Changed Field
            |--------------------------------------------------------------------------
            */

            $table->string('field')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Logical Path
            |--------------------------------------------------------------------------
            |
            | Example:
            | quotation.itineraries.{uuid}.items.{uuid}.unit_price
            |
            */

            $table->string('path')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Previous / New Values
            |--------------------------------------------------------------------------
            */

            $table->json('old_value')
                ->nullable();

            $table->json('new_value')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Action
            |--------------------------------------------------------------------------
            |
            | Examples:
            | created
            | updated
            | deleted
            |
            */

            $table->string('action');

            /*
            |--------------------------------------------------------------------------
            | User
            |--------------------------------------------------------------------------
            */

            $table->foreignId('user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Additional Information
            |--------------------------------------------------------------------------
            */

            $table->text('description')
                ->nullable();

            $table->ipAddress('ip_address')
                ->nullable();

            $table->text('user_agent')
                ->nullable();

            /*
            |--------------------------------------------------------------------------
            | Timestamps
            |--------------------------------------------------------------------------
            */

            $table->timestamps();

            /*
            |--------------------------------------------------------------------------
            | Indexes
            |--------------------------------------------------------------------------
            */

            $table->index('batch_uuid');

            $table->index([
                'entity_type',
                'entity_id',
            ]);

            $table->index([
                'entity_type',
                'entity_uuid',
            ]);

            $table->index('action');

            $table->index('user_id');

            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('histories');
    }
};
